networks:
  traefik-public:
    external: true

services:
  rdgen:
    image: bryangerlach/rdgen:latest
    restart: unless-stopped
    networks:
      - traefik-public
    env_file:
      - .env
    volumes:
      - ./exe:/opt/rdgen/exe
      - ./png:/opt/rdgen/png
      - ./temp_zips:/opt/rdgen/temp_zips
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
          - node.labels.rdgen == true
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.rdgen.rule=Host(`rdgen.itv34.ru`)'
        - 'traefik.http.routers.rdgen.entrypoints=http'
        - 'traefik.http.routers.rdgen.middlewares=https-redirect'
        - 'traefik.http.routers.rdgen-https.rule=Host(`rdgen.itv34.ru`)'
        - 'traefik.http.routers.rdgen-https.entrypoints=https'
        - 'traefik.http.routers.rdgen-https.tls=true'
        - 'traefik.http.routers.rdgen-https.tls.certresolver=le'
        - 'traefik.docker.network=traefik-public'
        - 'traefik.constraint-label=traefik-public'
        - 'traefik.http.services.rdgen-https.loadbalancer.server.port=8000'

